title: Pai Liu (刘派)
url: "https://pailiu1998.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-185054764-1

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=_sYc1cgAAAAJ&hl=en"
 - name: "Github"
   link: "https://github.com/pailiu1998"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/pai-liu-a2757110a"
 - name: "CV"
   link: "cv.pdf"
